# Generated by Django 4.2.3 on 2023-07-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('customer_id', models.IntegerField()),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('customer_type', models.CharField(choices=[('new', 'New Customer'), ('return', 'Return Customer'), ('private', 'Private')], max_length=15)),
                ('price', models.IntegerField()),
                ('product_table', models.JSONField(default=dict)),
                ('totalbuys', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('1', 'קרטון חד גלי 58/36/34'), ('2', 'קרטון דו גלי 55/32/30'), ('3', 'קרטון חד גלי 38/30/30'), ('4', 'קרטון חד גלי'), ('5', 'כפפות בלוקים כתומות'), ('6', 'כפפות לאטקס M'), ('7', 'כפפות לאטקס L'), ('8', 'סרט דבק 66'), ('9', ' שש יח סרט דבק 66'), ('10', 'מארז סרט דבק 72 66 יח'), ('11', 'not implied'), ('12', 'not implied'), ('13', 'not implied'), ('14', 'not implied'), ('15', 'not implied'), ('16', 'not implied'), ('17', 'not implied'), ('18', 'not implied'), ('19', 'not implied'), ('20', 'not implied'), ('21', 'not implied'), ('22', 'not implied'), ('23', 'not implied'), ('24', 'not implied'), ('25', 'not implied'), ('26', 'not implied'), ('27', 'not implied'), ('28', 'not implied'), ('29', 'not implied'), ('30', 'not implied'), ('31', 'not implied'), ('32', 'not implied'), ('33', 'not implied')], max_length=15)),
                ('over_all_stock', models.IntegerField()),
                ('price', models.IntegerField()),
                ('current_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sales_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('customer_id', models.IntegerField()),
                ('price', models.JSONField(default=dict)),
                ('product_table', models.JSONField(default=dict)),
                ('final_prize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('new_customer', models.JSONField(default=dict)),
                ('return_customers', models.JSONField(default=dict)),
                ('sum_of_sales', models.JSONField(default=dict)),
                ('bounus', models.JSONField(default=dict)),
            ],
        ),
    ]
