# Generated by Django 4.2.3 on 2023-07-14 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sales_history',
            new_name='SalesHistory',
        ),
    ]
