# Generated by Django 4.2.3 on 2023-07-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_sales_history_saleshistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='price',
            new_name='price_for_drivers',
        ),
        migrations.AddField(
            model_name='equipment',
            name='price_for_private',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
