# Generated by Django 4.2.3 on 2023-07-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_equipment_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='product_type',
            field=models.CharField(max_length=100),
        ),
    ]
