# Generated by Django 4.2.3 on 2023-07-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_equipment_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='price',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_for_drivers',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='price_for_private',
            field=models.FloatField(),
        ),
    ]
