# Generated by Django 4.2.3 on 2023-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_remove_customer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='totalbuys',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saleshistory',
            name='final_prize',
            field=models.FloatField(),
        ),
    ]
