# Generated by Django 4.2.3 on 2023-07-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_saleshistory_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleshistory',
            name='sales_man',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
