# Generated by Django 4.2.3 on 2023-07-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_alter_workers_bounus_alter_workers_new_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
