# Generated by Django 4.2.3 on 2023-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_equipment_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='notice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
