# Generated by Django 4.2.3 on 2023-07-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0012_equipment_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='origin_product',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
