# Generated by Django 4.2.3 on 2023-08-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_equipment_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleshistory',
            name='original_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
