# Generated by Django 4.2.3 on 2023-08-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_saleshistory_original_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleshistory',
            old_name='original_cost',
            new_name='profit',
        ),
    ]
